name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World"
      - name: Print Good Bye
        run: echo "Everything DONE! Good Bye!"
